### ISSUE TITLE
Installing on a Mac

### ISSUE THREAD

**Issue by CSchloss385** [FutureDays/qct-parse#6]
Hello! I can't wait to test out this tool! Do you have any instructions or tips on installing this on a mac? I'm having a problem installing "lxml."

**Comment by iamdamosuzuki** [comment]
you can use the python package manager pip to install 

`pip install lxml`

Let us know if this works!

**Comment by CSchloss385** [comment]
I ran:
sudo pip install lxml
and that seemed to do the trick. Thanks for your help!

**Comment by brnco** [comment]
Glad it worked, let us know what you think!

**Comment by CSchloss385** [comment]
I've been playing around with this today, and it's so cool! Just generated a bunch of thumbnails on a number of files I've been qc'ing and found some errors. Definitely something we'd like to add to the CUNY TV workflow.
