### ISSUE TITLE
multiple tags

### ISSUE THREAD

**Issue by CSchloss385** [FutureDays/qct-parse#7]
Are you able to analyze multiple tags, or is is just one at a time? For example, I typed this into terminal: 
python qct-parse.py -t SATMAX -o 124 -t YMIN -u 16 -i /Volumes/GDRIVE7/vrecord/BCLB000077/BCL01072_ffv1.mkv.qctools.xml.gz 
Starting Analysis on BCL01072_ffv1.mkv
Finished Processing File: BCL01072_ffv1.mkv.qctools.xml.gz
TotalFrames:	57543
By Tag:
YMIN:	57543	100	% of the total # of frames
Overall:
Frames With At Least One Fail:	0	0	% of the total # of frames

but it appear to only analyze the YMIN value.

**Comment by brnco** [comment]
Hey Catriona, for multiple tags you have to make a profile in the qct-parse_config.txt file. Then you would call it like:
python qct-parse.py -p your_profile /Volumes/GDRIVE7/vrecord/BCLB000077/BCL01072_ffv1.mkv.qctools.xml.gz

And the config text file would be modified like:
[your_profile]
SATMAX: 124
YMIN: 16

Note that thumbnail exporting for profiles is a bit buggy, see Issue #1 for details.

**Comment by CSchloss385** [comment]
Ah okay. That makes sense! Thanks again.

**Comment by brnco** [comment]
No problem, I'm going to close this out and update our README so this is more clear.
